server:
  port: 8082
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      mvc:
        routes:
          - id: author-service
            uri: lb://author-service
            predicates:
              - Path=/author/**
              - Method=GET
            filters:
              - RewritePath=/author/health, /health
          - id: book-service
            uri: lb://book-service
            predicates:
              - Path=/books/**
              - Method=GET
            filters:
              - RewritePath=/books/health, /health
          - id: eureka-service
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka-service-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern:
    console: '%msg%n'
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
